TARGET_EXEC := diec
TARGET_LIB := libdiec.so
TARGETS := $(TARGET_EXEC) $(TARGET_LIB)

# NOTE: This Makefile uses implicit gnumake rules and flags for c/cpp compilation
#
# Program for compiling C programs; default cc
CC := clang
# Program for compiling C++ programs; default g++
# CXX :=
# NOTE: CPP =/= C++ here
# Extra flags to give to the C preprocessor
CPPFLAGS := -MMD -MP
# Extra flags to give to the C compiler
CFLAGS := -std=c99 -Wall -Werror -include-pch
# Extra flags to give to the C++ compiler
# CXXFLAGS :=
# Extra flags to give to compilers when they are supposed to invoke the linker
# LDFLAGS :=

TESTFLAGS := -g -Og
SOFLAGS := -shared -fPIC
# LIBFLAGS := -L -l
# INCLFLAGS := -I

BUILD_DIR := ./build
SRC_DIR := ./src
# INCL_DIR := ./src/include
TEST_DIR := ./tests

SRCS := $(wildcard $(SRC_DIR)/*)
TESTS := $(wildcard $(TEST_DIR)/*)

SRC_OBJS := $(SRCS:$(SRC_DIR)/%.c=$(BUILD_DIR)/%.o)
TEST_OBJS := $(TESTS:$(TEST_DIR)/%.c=$(BUILD_DIR)/%.o)

SRC_DEPS := $(SRC_OBJS:.o=.d)
TEST_DEPS := $(TEST_OBJS:.o=.d)
BUILD_DEPS := $(SRC_DEPS) $(TEST_DEPS)

PRECOMP_H := $(BUILD_DEPS:.d=.pch)

install: $(TARGET_EXEC)
lib: $(TARGET_LIB)
all: test $(TARGET_EXEC) $(TARGET_LIB)
clean:
	rm -rf test $(TARGET_EXEC) $(TARGET_LIB) $(BUILD_DIR)

$(TARGET_EXEC): $(SRCS)
	$(CC) $(CFLAGS) -o $(TARGET_EXEC) $(SRCS)

$(TARGET_LIB): $(SRCS)
	$(CC) $(CFLAGS) $(SOFLAGS) -o $(TARGET_LIB) $(SRCS)

test: $(TESTS)
	$(CC) $(CFLAGS) $(TESTFLAGS) -o test $(TESTS)

$(TEST_OBJS): $(TEST_OBJS:.o=.c)
$(SRC_OBJS): $(SRC_OBJS:.o=.c)

$(PRECOMP_H): $(PRECOMP_H:.pch=.o)

# NOTE: Runs the BUILD_DEPS Makefiles auto-generated by -MMD -MP flags
-include $(BUILD_DEPS)

.PHONY: all clean install lib

